### ISSUE TITLE
How to get listed as autofill service in playstore?

### ISSUE THREAD

**Issue by mani516** [commonsguy/AutofillFollies#2]
`However, we’ll have a manual procedure in place to verify such compliance for apps that want to be list as an Autofill service option in the “Add Autofill Service” Play Store page that is launched from Settings.`

Hey, do you have any idea on how any app can apply for this compliance? I am working on a password manager app and implemented autofill service to autofill app logins. 

I would like my app get listed in playstore as autofill service. Can you help?

**Comment by commonsguy** [comment]
> Hey, do you have any idea on how any app can apply for this compliance?

No, sorry.
